### ISSUE TITLE
Using LWP::Protocol::https directly

### ISSUE THREAD

**Issue by oalders** [maxmind/ccfd-api-perl#4]
Why are we using LWP::Protocol::https directly in Business::MaxMind::HTTPBase?

https://metacpan.org/source/Business::MaxMind::HTTPBase#L7

Possibly related issue https://github.com/oalders/business-paypal-api/issues/10

**Comment by oschwald** [comment]
Looks like @mateu [did this](https://github.com/maxmind/ccfd-api-perl/commit/27cfbeb2bfd9ea38f80da52d5de2e15c1f8d1684) to force it as a dependency.

**Comment by oalders** [comment]
Ah.  Might have been less confusing to add the dependency to `dist.ini`

**Comment by oschwald** [comment]
PR welcome ;-)
